name: tamanavi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  uuid: ^4.5.1
  freezed_annotation: ^2.0.0
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.2
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.3
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  flutter_lints: ^5.0.0
  freezed: ^2.0.0
  very_good_analysis: ^10.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/rounded-x-mgenplus-2c-black.ttf
    - assets/images/ball.svg
    - assets/images/玉.svg
    - assets/images/ナ.svg
    - assets/images/ビ.svg

